name: flexitask_updated
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.1.4
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.0
  cupertino_icons: ^1.0.2
  cloud_firestore: ^5.6.7
  http: ^1.2.2
  intl: ^0.19.0

  # Add these packages
  permission_handler: ^12.0.0 # Use this specific version
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/ # Add this line for the sounds directory

  fonts:
    - family: Lexend
      fonts:
        - asset: fonts/static/Lexend-Regular.ttf
        - asset: fonts/static/Lexend-Bold.ttf
          weight: 700
        - asset: fonts/static/Lexend-Medium.ttf
          weight: 500
        - asset: fonts/static/Lexend-SemiBold.ttf
          weight: 600

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true
