// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQVsOktah68XMCffMUuQmKZXyoAJCTvfM',
    appId: '1:161145697554:android:01c6094268cdd6c997afcb',
    messagingSenderId: '161145697554',
    projectId: 'flexi-task-5d512',
    storageBucket: 'flexi-task-5d512.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfLRO1RiaiNbFeAcKhT2ILSnMbAaFP8Zc',
    appId: '1:211642642283:ios:a10f88acfa74c8e527e62e',
    messagingSenderId: '211642642283',
    projectId: 'flexi-task-4fb2a',
    databaseURL:
        'https://flexi-task-4fb2a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flexi-task-4fb2a.firebasestorage.app',
    iosBundleId: 'com.example.flexitaskMobile',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAhcqyzf8x1FXd0Zqka12t_NQaoCEWD44',
    appId: '1:161145697554:web:23d9c0c67426e92a97afcb',
    messagingSenderId: '161145697554',
    projectId: 'flexi-task-5d512',
    authDomain: 'flexi-task-5d512.firebaseapp.com',
    storageBucket: 'flexi-task-5d512.firebasestorage.app',
    measurementId: 'G-N96T1YNNXG',
  );

}